function scene(){this.solid=[];this.observer=[0,0,0];this.distance=-1000}
var world=new scene();var canvas,ctx;var alpha=1;var showGrid=/showgrid/.test(location.href);var allFaces=[];var skin={};var player={hat:{},head:{},body:{},left_arm:{},right_arm:{},left_leg:{},right_leg:{},item:{}};var offset={x:200,y:130};var filterLayer;var reverseMap;var itemsPNG="/images/items.png";$(function(){var g;if(g=location.hash.match(/screenshot\(([^)]+)\)/)){try{$("#screenshot").attr("src",g[1]);}catch(f){}}
canvas=document.getElementById("display");ctx=canvas.getContext("2d");imageData=ctx.createImageData(64,32);testIsPointInPathIssue();createModel();skin.canvas=$("#skin")[0];skin.ctx=skin.canvas.getContext("2d");skin.imageData=skin.ctx.getImageData(0,0,64,32);skin.map={};skin.map.canvas=$("#skinMap")[0];skin.map.ctx=skin.map.canvas.getContext("2d");document.onkeydown=onKeyDown;canvas.onmousedown=onMouseDown;canvas.onmouseup=onMouseUp;canvas.onmousemove=onMouseMove;canvas.oncontextmenu=function(){return false};if(animating)canvas.onclick=play;loadSkinUrl(getSkinFromUrl()||"http://minecraft.net/img/char.png");positionate();var c;if(c=location.hash.match(/item\(([^)]+)\)/)){var d,b;if(d=c[1].split(",")[1]){itemsPNG=d}
if(b=c[0].match(/item\((\d+)/)){b=Number(b[1])}else{if(b=c[0].match(/item\((\w+)/)){b=itemNames[b[1]]}}
loadItem({left:(b%(256/16))*16,top:Math.floor(b/16)*16})}
$(window).resize(function(e){updateCanvasSize()});updateCanvasSize();$("#item").click(function(){$("head").append('<link rel="stylesheet" href="js/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen"/>');jQuery.getScript("js/fancybox/jquery.fancybox-1.3.4.pack.js",function(){$("#item").unbind("click").click(function(){$.fancybox('<img id="itemsImage" src="'+ itemsPNG+'" width="256" height="256"/><div id="sel" style="position: absolute; top:0; left: 0;   background-color: rgba(0, 0, 255, 0.4); box-shadow: 0 0 10px blue; width: 16px; height: 16px">');$("#itemsImage").mousemove(function(h){$("#sel").css({left:Math.floor(h.layerX/16)*16,top:Math.floor(h.layerY/16)*16})});$("#sel").click(function(){var e=$("#sel").position();$.fancybox.close();loadItem(e)})}).click()})});$("#skinMap").click(function(){$(".skin").animate({width:64*8,height:32*8}).attr("title","").css("cursor","crosshair");$("#hideSkin").show()}).attr("title","click to enlarge").css("cursor","hand");$("#hideSkin").click(function(){$(this).hide();$(".skin").animate({width:64,height:32}).attr("title","click to enlarge").css("cursor","hand")});$(".bottom").delay(20000).animate({height:"10px"}).mouseenter(function(){$(this).animate({height:"70px"})}).mouseleave(function(){$(this).animate({height:"10px"})});$("#translate").mousedown(function(e){var h={x:e.pageX,y:e.pageY};$(document).bind("mousemove",function(i){var j={x:i.pageX,y:i.pageY};ctx.translate((j.x- h.x),(j.y- h.y));offset.x+=(j.x- h.x);offset.y+=(j.y- h.y);draw();h=j})});$("#rotate").mousedown(function(e){var h={x:e.pageX,y:e.pageY};$(document).bind("mousemove",function(i){var j={x:i.pageX,y:i.pageY};rotatePlayer(0,(j.y- h.y)/100,(j.x- h.x)/100);draw();h=j})});$("#rotateleft").bind('click touchstart',function(){rotatePlayer(-Math.PI/8,0,0);draw();return false;});$("#rotateright").bind('click touchstart',function(){rotatePlayer(Math.PI/8,0,0);draw();return false;});$("#scale").mousedown(function(e){var h={y:e.pageY};$(document).bind("mousemove",function(i){var j={y:i.pageY};world.distance+=(j.y- h.y)*10;if(world.distance>-150){world.distance=-150}
draw();h=j})});$("#zoomin").bind('click touchstart',function(){world.distance+=300;draw()});$("#zoomout").bind('click touchstart',function(){world.distance-=300;draw()});$("#coord").mousedown(function(){$(".cover").show()});$(document).mouseup(function(){$(document).unbind("mousemove");$(".cover").hide()});for(var a in positions){$("<option>").attr("value",a).text(a).appendTo("#position")}
$("#position").change(function(){changePosition(positions[$(this).attr("value")]);draw()})});function createModel(playerItem){function shareColors(source,destination){for(var part in source){for(var i=0;i<Math.min(source[part].length,destination[part].length);i++){destination[part][i].fillcolor=source[part][i].fillcolor;destination[part][i].linecolor=source[part][i].linecolor;destination[part][i].map=source[part][i].map}}}
player={hat:hatCubes(0.4),head:headCubes(),body:bodyCubes()};with(legCubes()){player.left_leg=left;player.right_leg=right}
with(armCubes()){player.left_arm=left;player.right_arm=right}
shareColors(player.left_arm,player.right_arm);shareColors(player.left_leg,player.right_leg);setGroups(player);if(playerItem){for(var p in playerItem){player.left_arm[p]=player.left_arm[p].concat(playerItem[p])}}
showPart("all");allFaces=world.solid;makeReverseMapping();delete changePosition.old;draw()}
function loadItem(pos){var img=new Image();var id=pos.top+ pos.left/16;img.onload=function(){var c=$('<canvas>').attr({width:img.width,height:img.height})[0].getContext('2d');c.drawImage(img,0,0,img.width,img.height);var item=c.getImageData(pos.left,pos.top,16,16);createModel(itemCubes(item,/^(42|43|44|64|65|66|67|68|69|21|37|53|69|85|101|117|133|79|80|81|82|83|84|96|97|98|99|100|112|113|114|115|116|128|129|130|131|132|38|86|22|23|24|25|26|28|39|41|87|88|91|92|93|105|106|108|109|110|121|122|142|2[45]\d)$/.test(id)));updateCubeColors();draw();}
img.src=itemsPNG;playerItem=itemNames[id]||id;}
function positionate(){var c;if(c=location.href.match(/pose[(=]([^)&]+)\)?/)){try{c=c[1];changePosition(positions[c]||JSON.parse(decodeURIComponent(c.replace(/(\w+):/g,'"$1":'))))}catch(b){}}
var a;if(a=location.hash.match(/angle\(-?\d+,-?\d+,-?\d+\)/)){a=a[0].match(/-?\d+/g);rotatePlayer((a[0]||0)*Math.PI/180,(a[1]||0)*Math.PI/180,(a[2]||0)*Math.PI/180)}}
function showPart(part,show){world.solid=[];function concatCubes(cubes){with(cubes){world.solid=world.solid.concat(left).concat(right).concat(top).concat(bottom).concat(front).concat(back)}}
if(part!="all"){showPart[part]=show}
for(var p in player){if(showPart[p]||part=="all"){showPart[p]=true;concatCubes(player[p])}}
draw()}
function setGroups(){function a(c){for(var b in c){$(c[b]).each(function(e,d){d.layer=c[b]})}}
a(player.hat);a(player.head);a(player.left_arm);a(player.right_arm);a(player.body);a(player.left_leg);a(player.right_leg)}
function makeReverseMapping(){reverseMap=new Array(64);allFaces.forEach(function(a){if(a.map){if(!reverseMap[a.map.x]){reverseMap[a.map.x]=new Array(32)}
reverseMap[a.map.x][a.map.y]=a}})}
function testIsPointInPathIssue(){ctx.translate(-1000,-1000);ctx.moveTo(0,0);ctx.lineTo(10,0);ctx.lineTo(10,10);ctx.lineTo(0,10);translateThePoint=ctx.isPointInPath(5,5);ctx.translate(1000,1000)}
function getSkinFromUrl(){return document.location.hash.replace("#","").split(";")[0]}
function updateCanvasSize(){canvas.width=$(window).width();canvas.height=$(window).height()- $(canvas).position().top;offset={x:canvas.width/2- 35,y:canvas.height/2- 70};ctx.translate(offset.x,offset.y);draw()}
function onKeyDown(a){}
var clicked,lastCursorPosition={},lastClick={};function onMouseDown(c){var b=c.pageX- canvas.offsetLeft;var d=c.pageY- canvas.offsetTop;var a={x:b-(translateThePoint?offset.x:0),y:d-(translateThePoint?offset.y:0)};lastClick=lastCursorPosition={x:b,y:d};if(c.shiftKey||c.altKey){canvas.onmousemove=function(f){var e=f.pageX- canvas.offsetLeft;var g=f.pageY- canvas.offsetTop;ctx.translate((e- lastCursorPosition.x),(g- lastCursorPosition.y));offset.x+=(e- lastCursorPosition.x);offset.y+=(g- lastCursorPosition.y);lastCursorPosition={x:e,y:g};draw()}}
clicked=a;draw();c.preventDefault()}
n=0;function onMouseUp(a){canvas.onmousemove=onMouseMove;clicked=null;filterLayer=null;draw()}
function onMouseMove(b){var a=b.pageX- canvas.offsetLeft;var c=b.pageY- canvas.offsetTop;if(b.shiftKey||b.altKey||clicked){rotatePlayer((a- lastCursorPosition.x)/100,(c- lastCursorPosition.y)/100);draw()}
lastCursorPosition={x:a,y:c}}
function rotatePlayer(b,h,g){var f=player.body.front[0].axis_y.concat();var e=player.body.front[0].axis_z.concat();var d=[this.player.body.back[12*8- 1].points[0],this.player.body.front[0].points[0]];var a=[d[0][0]+(d[1][0]- d[0][0])/2,d[0][1]+(d[1][1]- d[0][1])/2,d[0][2]+(d[1][2]- d[0][2])/2];for(var c=0;c<allFaces.length;c++){rotate_solid(a,f,b,allFaces[c]);rotate_solid_x(a,h,allFaces[c]);if(g){rotate_solid(a,e,-g,allFaces[c])}}}
function setupWheel(){$(canvas).wheel(function(a,b){if(a.shiftKey||a.altKey){world.distance-=b*360}else{rotatePlayer(b*Math.PI/6,0,0)}
draw();a.preventDefault()})}
function getPixel(a,b){index=(a+ b*skin.imageData.width)*4;return[skin.imageData.data[index+ 0],skin.imageData.data[index+ 1],skin.imageData.data[index+ 2],skin.imageData.data[index+ 3]]}
function updateCubeColors(){skin.imageData=skin.ctx.getImageData(0,0,64,32);$(allFaces).each(function(c,a){if(a.map){var b=getPixel(a.map.x,a.map.y);a.fillcolor[0]=b[0];a.fillcolor[1]=b[1];a.fillcolor[2]=b[2];a.fillcolor[3]=b[3]>32?255:0}})}
var originalServer="http://minecraft.novaskin.me/getimagedata?callback=?";var imagedataServer=originalServer;function loadSkin(i,c,j,g,b){var d=i.match(/s3.amazonaws.com\/MinecraftSkins\/(.*)\.png/);if(d){d=d[1]}
var e=document.location.href.replace(/#.*$/,"");if(!b){document.location.href=e+(c?(document.location.hash||"#")+"+":"#")+(d?d:i)}
$("#skinUrl").val((d?d:i));function a(k){if(!c){skin.ctx.clearRect(0,0,skin.canvas.width,skin.canvas.height)}
skin.ctx.drawImage(k,0,0,k.width,k.height);updateCubeColors();draw();if(j){j()}}
function f(){imagedataServer=(imagedataServer==""?originalServer:"");if(g){g()}}
function h(){serverGetImageData(i,a,f)}
yqlGetImageData(i,a,h)}
function yqlGetImageData(url,success,error,extra){$.ajax({url:'http://query.yahooapis.com/v1/public/yql?format=json&q=select%20*%20from%20data.uri%20where%20url%3D%40url',data:{url:url},dataType:'jsonp',jsonp:'callback',jsonpCallback:'yqlCallback',cache:true,error:error,timeout:5000});yqlCallback=function(data){try{if(!data||!data.query||!data.query.results||data.query.results.error||!data.query.results.url){error();}else{var image=new Image();image.onload=function(){success(image,url,extra);};image.src=data.query.results.url;}}catch(e){error();}}}
function serverGetImageData(url,success,error,extra){$.getImageData({server:'http://minecraft.novaskin.me/getimagedata?callback=?',url:url.replace('https','http'),success:function(img){success(img,url,extra);},error:error});}
function loadUserSkin(b,d,c,a){loadSkin("http://s3.amazonaws.com/MinecraftSkins/"+ b+".png",false,d,c,a)}
function loadSkinUrl(c){var g=$(c.split("+"));var e=[];var d;function f(){if(++d<g.length){a(d)}}
function b(){e[d]=(e[d]||0)+ 1;if(e[d]>3){informError(g[d]);}else{a(d)}}
function a(h){if(!g[h].match(/http/)){loadUserSkin(g[h],f,b,true)}else{loadSkin(g[h],h>0,f,b,true)}}
d=0;a(d)}
function draw(){if(ctx){var g=0;var k=[];var d;var c;var b;for(var e=0;e<world.solid.length;e++){for(var f=0;f<world.solid[e].faces_number;f++){d=(world.solid[e].points[world.solid[e].faces[f][0]][0]+ world.solid[e].points[world.solid[e].faces[f][2]][0])/2- world.observer[0];c=(world.solid[e].points[world.solid[e].faces[f][0]][1]+ world.solid[e].points[world.solid[e].faces[f][2]][1])/2- world.observer[1];b=(world.solid[e].points[world.solid[e].faces[f][0]][2]+ world.solid[e].points[world.solid[e].faces[f][2]][2])/2- world.observer[2];k[g++]={solid:e,vertex:world.solid[e].faces[f],fillcolor:world.solid[e].fillcolor,linecolor:world.solid[e].linecolor,distance:d*d+ c*c+ b*b}}}
k.sort(function(j,i){return i.distance- j.distance});var h=[];for(var e=0;e<world.solid.length;e++){h[e]=[];for(var f=0;f<world.solid[e].points_number;f++){h[e][f]=project(world.distance,world.solid[e].points[f])}}
ctx.clearRect(-1000,-1000,2000,2000);var a={x1:1/0,y1:1/0,x2:-1/0,y2:-1/0};function l(p){var o=k[p];var q=h[o.solid];var r=o.vertex;var j=world.solid[o.solid];var m=filterLayer&&j.layer!==filterLayer;ctx.fillStyle="rgb("+ o.fillcolor[0]+","+ o.fillcolor[1]+","+ o.fillcolor[2]+")";ctx.strokeStyle=showGrid?"rgb("+ o.linecolor[0]+","+ o.linecolor[1]+","+ o.linecolor[2]+")":ctx.fillStyle;ctx.beginPath();ctx.moveTo(q[r[0]][0],q[r[0]][1]);ctx.lineTo(q[r[1]][0],q[r[1]][1]);ctx.lineTo(q[r[2]][0],q[r[2]][1]);ctx.lineTo(q[r[3]][0],q[r[3]][1]);ctx.globalAlpha=m?0.2:o.fillcolor[3]/255;ctx.fill();if(showGrid){ctx.globalAlpha=m?0:filterLayer?1:0.6}
ctx.stroke();if(clicked&&ctx.isPointInPath(clicked.x,clicked.y)){clicked.cube=j;clicked.polygon=p}
if(clicked&&clicked.tool&&j.layer===filterLayer&&ctx.isPointInPath(clicked.tool.to.x,clicked.tool.to.y)){clicked.tool.clickedCube=world.solid[o.solid];clicked.tool.clickedPolygon=p}
a.x1=Math.min(a.x1,q[r[0]][0],q[r[2]][0]);a.x2=Math.max(a.x2,q[r[1]][0],q[r[3]][0]);a.y1=Math.min(a.y1,q[r[0]][1],q[r[2]][1]);a.y2=Math.max(a.y2,q[r[1]][1],q[r[3]][1])}
for(var f=0;f<g;f++){l(f)}}
return a}
function informError(skin){var screenshot;if(screenshot=location.hash.match(/screenshot\(([^)]+)\)/))
screenshot=screenshot[1];if(screenshot){$(document.body).css({'background':'url('+ screenshot+') center center','background-size':'auto 80%','background-repeat':'no-repeat'});}
$('#toolbar').css({'height':'60px','text-align':'center','vertical-align':'middle','padding-top':'40px','visibility':'visible'}).html('Could not load skin '+ skin);}
function touchHandler(c){var d=c.changedTouches,e=d[0],a="";switch(c.type){case"touchstart":a="mousedown";break;case"touchmove":a="mousemove";break;case"touchend":a="mouseup";break;default:return}
var b=document.createEvent("MouseEvent");b.initMouseEvent(a,true,true,window,1,e.screenX,e.screenY,e.clientX,e.clientY,false,false,false,false,0,null);switch(c.type){case"touchstart":onMouseDown(b);break;case"touchmove":onMouseMove(b);break;case"touchend":onMouseUp(b);break}
if(c.type=="touchmove"){c.preventDefault()}}
$(function(){document.addEventListener("touchstart",touchHandler,true);document.addEventListener("touchmove",touchHandler,true);document.addEventListener("touchend",touchHandler,true);document.addEventListener("touchcancel",touchHandler,true)});
